# Generated by Django 3.1.7 on 2021-04-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210420_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='heart',
        ),
        migrations.RemoveField(
            model_name='event',
            name='heart_cnt',
        ),
    ]
