# Generated by Django 3.1.7 on 2021-05-12 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('report', models.IntegerField(blank=True, default=0)),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoshop_post.shoppost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop-post')),
                ('shop_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoshop_post.shoppost')),
            ],
        ),
        migrations.AddField(
            model_name='shoppost',
            name='shop_post_likes_user',
            field=models.ManyToManyField(related_name='shop_post_likes_user', through='ecoshop_post.ShopPostLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
