# Generated by Django 3.1.7 on 2021-03-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='heart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='heart_cnt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
