# Generated by Django 3.1.7 on 2021-04-02 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0002_auto_20210326_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoshop.shop')),
            ],
        ),
    ]
