# Generated by Django 3.1.7 on 2021-04-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0003_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='report',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
