# Generated by Django 3.1.7 on 2021-04-20 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoshop', '0005_auto_20210420_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppost',
            name='like_users',
            field=models.ManyToManyField(related_name='likes_user', through='ecoshop.ShopPostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
