# Generated by Django 3.1.7 on 2021-04-21 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoshop', '0007_auto_20210420_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppost',
            name='likes_user',
        ),
        migrations.RemoveField(
            model_name='shoppostlike',
            name='created_date',
        ),
        migrations.AddField(
            model_name='shoppost',
            name='shop_post_likes_user',
            field=models.ManyToManyField(related_name='shop_post_likes_user', through='ecoshop.ShopPostLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoshop.shop'),
        ),
    ]
