# Generated by Django 3.1.7 on 2021-05-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0010_auto_20210422_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppostimage',
            name='shop_post',
        ),
        migrations.RemoveField(
            model_name='shoppostlike',
            name='shop_post',
        ),
        migrations.RemoveField(
            model_name='shoppostlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShopPost',
        ),
        migrations.DeleteModel(
            name='ShopPostImage',
        ),
        migrations.DeleteModel(
            name='ShopPostLike',
        ),
    ]
