# Generated by Django 3.1.7 on 2021-04-06 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('heart_cnt', models.IntegerField(blank=True, default=0)),
                ('heart', models.BooleanField(blank=True, default=False)),
                ('report', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop-post')),
                ('shop_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoshop.shoppost')),
            ],
        ),
    ]
