# Generated by Django 3.1.7 on 2021-04-06 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoshop.shoppost'),
        ),
    ]
