# Generated by Django 3.1.7 on 2021-04-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0002_auto_20210406_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppost',
            name='nickname',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
