# Generated by Django 3.1.7 on 2021-04-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0003_auto_20210406_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppost',
            name='heart',
        ),
        migrations.RemoveField(
            model_name='shoppost',
            name='heart_cnt',
        ),
    ]
